export {default as image1 } from'./karigurashi007.jpg'
export {default as image2 } from'./karigurashi026.jpg'
export {default as image3 } from'./karigurashi045.jpg'
export {default as image4 } from'./majo010.jpg'
export {default as image5 } from'./ponyo028.jpg'